import json
import pprint

def store_json_data(dict_data, file_name):
    """writes data to JSON file"""
    with open(file_name, 'w') as json_file:
        json.dump(dict_data, json_file)


def dict_to_file(data_dict, file_name):
    """
    Save a dictionary to a Python file as a variable named 'companies_dict'.

    Args:
        data_dict (dict): The dictionary to save.
        file_name (str): The name of the Python file to save the dictionary in.
    """
    try:
        with open(file_name, 'w', encoding='utf-8') as file:
            # Write a header comment
            file.write("# This file is generated by dict_to_file\n")
            file.write("# It contains the companies_dict variable.\n\n")

            # Write the dictionary to the file
            file.write("companies_dict = ")
            pprint.pprint(data_dict, stream=file, indent=4, width=120)

        print(f"Dictionary successfully saved to {file_name}")
    except Exception as e:
        print(f"An error occurred: {e}")


