import json
import os
import pprint
from typing import Union

from config import JSON_OUTPUT_FILE, PY_OUTPUT_FILE


def store_json_data(dict_data, file_name):
    """writes data to JSON file"""
    with open(file_name, 'w') as json_file:
        json.dump(dict_data, json_file)


def store_dict_data(data_dict, file_name: Union[str, bytes]) -> None:
    """
    Save a dictionary to a Python file as a variable named 'companies_dict'.

    Args:
        data_dict (dict): The dictionary to save.
        file_name (str): The name of the Python file to save the dictionary in.
    """
    try:
        with open(file_name, 'w', encoding='utf-8') as file:
            # Write a header comment
            file.write("# This file is generated by dict_to_file\n")
            file.write("# It contains the companies_dict variable.\n\n")

            # Write the dictionary to the file
            file.write("companies_dict = ")
            pprint.pprint(data_dict, stream=file, indent=4, width=120)

        print(f"Dictionary successfully saved to {file_name}")
    except Exception as e:
        print(f"An error occurred: {e}")

def save_to_file(tase_dict, file_path):
    # Ensure the output directory exists
    os.makedirs(file_path, exist_ok=True)

    # Define the file path for the file to be saved
    json_file_path = os.path.join(file_path, JSON_OUTPUT_FILE)
    py_file_path = os.path.join(file_path, PY_OUTPUT_FILE)

    store_json_data(tase_dict, json_file_path)
    store_dict_data(tase_dict, py_file_path)

    print(f"Created files: '{json_file_path}', and '{py_file_path}'")

